### ISSUE TITLE
require "*" failed but "dev-main" succeed

### ISSUE THREAD

**Issue by littlegolden** [afrux/forum-stats-widget#1]
run `composer require afrux/forum-stats-widget:"*"` throw an error, changed to "dev-main" can install successfully.

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires afrux/forum-stats-widget *, found afrux/forum-stats-widget[dev-main] but it does not match your minimum-stability.
```

**Comment by SychO9** [comment]
You must have your composer json configured as dev mode or something.

What's its contents?

**Comment by littlegolden** [comment]
I think I'm not in dev mode, cause only this one has that error
```json
{
    "require": {
        "afrux/forum-stats-widget": "dev-main",
        "afrux/forum-widgets-core": "*",
        "afrux/news-widget": "*",
        "afrux/online-users-widget": "*",
        "afrux/top-posters-widget": "*"
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
```

**Comment by SychO9** [comment]
Well, there's definitely something about your setup 😬, there is nothing special about how this extension is released, it's the same as every other one. Don't use dev main if you can't figure it out, never use a dev version.
